version: "3.7"
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./workspace/app:/usr/local/app
    ports:
      - "8000:8000"
    working_dir: /usr/local/app
